export const types = {
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_EMAIL_VERIFIED: 'SET_EMAIL_VERIFIED',
  SET_PAGE_TITLE: 'SET_PAGE_TITLE',
  SET_REFRESH_TOKEN: 'SET_REFRESH_TOKEN',
  SET_USER_COMP_DATA: 'SET_USER_COMP_DATA',
  SET_USERNAME: 'SET_USERNAME'
}